{'locations': [{
    'score': 150, 
    'countryCodeAlpha3': 'ZAF',
     'countryCodeAlpha2': 'ZA',
      'cityPopulation': 49292,
       'stateAnsiCode': '06',
        'pointGeometry': '0101000020E6100000029F1F4608273C40075F984C15243AC0',
         'cityNameAscii': 'Edenvale', 'stateIsoCode': 'ZA-06',
          'countryName': 'South Africa',
           'stateName': 'Gauteng',
            'longitude': 28.15247,
             'geonameId': 1006834,
              'latitude': -26.14095,
               'cityName': 'Edenvale',
                'type': 'city',
                 'id': 'EDENVALE-ZA-06-KEK529HJBJEP78PMHV0U',
                  'geofeed': '169.255.0.135,ZA,ZA-06,Edenvale,'}
], 'metadata': {
    'environment': 'production',
     'distribution': {},
      'service': {
    'version': '18.11.16.2',
     'contributions': {'
     169.255.0.135': {'
     engines': [{'engine': 'probeslocation',
      'type': 'probes',
       'empty': False,
        'metadata': {}},
        {'engine': 'crowdsourced',
         'type': 'crowdsource',
          'empty': True,
           'metadata': {}},
            {'engine': 'single-radius',
             'type': 'active',
              'empty': False,
               'metadata': {
                   'locating': False,
                    'message': ''}},
                     {'engine': 'simple-anycast',
                      'type': 'active',
                       'empty': True,
                        'metadata': {
                            'anycast': False,
                             'locating': None}},
                              {'engine': 'ixp',
                               'type': 'ixp',
                                'empty': True,
                                 'metadata': {}}]}}},
                                  'request': {'params': {'ip': '169.255.0.135'},
                                   'query': {}}}}
